"""add tables

Revision ID: c79d1dd52e10
Revises: 
Create Date: 2023-02-19 02:45:44.515134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c79d1dd52e10"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("email", sa.TEXT(), nullable=True),
        sa.Column("password", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "themes",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("title", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("title", sa.TEXT(), nullable=True),
        sa.Column("theme_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(["theme_id"], ["themes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "answers",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("title", sa.TEXT(), nullable=True),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.Column("question_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("answers")
    op.drop_table("questions")
    op.drop_table("themes")
    op.drop_table("admins")
    # ### end Alembic commands ###
